name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-push:
    strategy:
      matrix:
        target: [base, docker]

    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: gitea.antoine-langlois.net
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          target: ${{ matrix.target }}
          tags: |
            ${{ gitea.repository_owner }}/${{ gitea.repository }}:${{ matrix.target }}
            gitea.antoine-langlois.net/${{ gitea.repository_owner }}/${{ gitea.repository }}:${{ matrix.target }}
